### ISSUE TITLE
Need to better document new programmer directory structure and usage.

### ISSUE THREAD

**Issue by samuelcomeau6** [tinyfpga/TinyFPGA-B-Series#12]
This file randomly looks it should be executed. (Would be nice if documentation even mentioned it) 
These are the results:
./setup.py
from: too many arguments
./setup.py: line 2: syntax error near unexpected token `newline'
./setup.py: line 2: `setup('

So doesn't work.

**Comment by tinyfpga** [comment]
That’s part of the tinyfpgab Python package.  Here’s a tutorial on python packaging: http://python-packaging.readthedocs.io/en/latest/minimal.html.

I’ll update the documentation to explain the directory structure and how to use the tinyfpgab module directly from the git repo if desired.

**Comment by tinyfpga** [comment]
I've added a quick explanation of what setup.py is in the updated README.md: https://github.com/tinyfpga/TinyFPGA-B-Series/blob/master/programmer/README.md

**Comment by tinyfpga** [comment]
I believe this is fixed.  Please re-open if you believe otherwise.
