### ISSUE TITLE
tinyfpgab --boot works only after the second execution

### ISSUE THREAD

**Issue by afiskon** [tinyfpga/TinyFPGA-B-Series#14]
For some reason the first execution has no effect with B2 board.

**Comment by cr1901** [comment]
I can confirm this on Windows 7 using libwdi's `usbser.sys` driver. Though I could've sworn in the past the `tinyfpgab -b` boot invocation worked the first time, neither my Nov 10 copy nor Nov 1st copy of the repo function correctly (i.e. they both require me to pass `--boot` twice).

In addition the device does not detach from the bus after the user bitstream is loaded.

**Comment by tinyfpga** [comment]
This won't be fixed in this legacy version of the bootloader.  However it is fixed in https://github.com/tinyfpga/TinyFPGA-Bootloader/ and there will be an upgrade process at some point to upgrade the B2 boards from the legacy bootloader to the new one.
