### ISSUE TITLE
Wrong VID:PID

### ISSUE THREAD

**Issue by donnie-j** [tinyfpga/TinyFPGA-B-Series#3]
B2 boards which arrived this week have a different VID:PID than is expected by the programmer.  Here is a patch that allows the programmer to detect the board.

```diff --git a/programmer/tinyfpgab-programmer.py b/programmer/tinyfpgab-programmer.py
index 8b0d8ca..5b33579 100644
--- a/programmer/tinyfpgab-programmer.py
+++ b/programmer/tinyfpgab-programmer.py
@@ -78,7 +78,7 @@ def update_serial_port_list_task():
     global program_in_progress
     
     if not program_in_progress:
-        new_tinyfpga_ports = [i[0] for i in comports() if "1209:1200" in i[2]]
+        new_tinyfpga_ports = [i[0] for i in comports() if "1209:2100" in i[2]]
 
         if new_tinyfpga_ports != tinyfpga_ports:
             if com_port_sv.get() == "" and len(new_tinyfpga_ports) > 0:```

I still have a problem generating an Intel Hex file from the Yosys tools that the programmer will accept.  It's not clear to me if it's (say) a question of selecting the correct Intel Hex base address, or if the issue is communication with the board.

**Comment by tinyfpga** [comment]
Hey @donnie-j, thanks for these issues and patches, I'll be reviewing and merging them shortly.  

If you attach a hex file to a new issue and I'll try and reproduce the problem you are running into.

**Comment by tinyfpga** [comment]
Another thing I remembered, the programmer application parses .hex files.  The .hex files are just a whitespace-seperated list of byte values starting at the least significant byte.  It does not currently support Intel hex files (with a .mcs extension).  I can add support for Intel hex this weekend.

**Comment by donnie-j** [comment]
Thanks for this.

Actually I had figured out that .hex was not Intel hex.  If you are working on this, I think it is better (from a yosys point of view) to add a binary file reader.  I might post a patch if I get some time :)

**Comment by tinyfpga** [comment]
Yeah, I really just want it to work without much fuss for anyone.  A [pull-request](https://help.github.com/articles/about-pull-requests/) for binary files would be awesome.  I'll be adding support for the [TinyFPGA Programmer](https://github.com/tinyfpga/TinyFPGA-A-Programmer) to the GUI this weekend so I'll be making some commits.

**Comment by tinyfpga** [comment]
I moved the programmer GUI to the [TinyFPGA Programmer repo](https://github.com/tinyfpga/TinyFPGA-Programmer-Application) which has the correct PID and VID.
